Iris dataset Classification using Naive Bayes Algorithm

In [51]:
#importing all packages
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [52]:
#Loading the Iris dataset using the 'read_csv()' function from pandas library
#The read_csv() function read the contents of a dataset stored in .csv or comma separated values format
data = pd.read_csv("Iris.csv")

#Checking if the dataset was read properly
print(data.head())

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa


In [53]:
#Our prediction target or dependent variable is the 'Species' column
#Separating the dependent variable and the independent variables using dataframe slicing techniques from pandas library
X = data.iloc[:,1:5].values #Set of independent variables
y = data['Species'].values #Dependent variable

In [54]:
#Splitting the dataset into Training Set and Testing Set
#Using the 'train_test_split' function from sklear library
#The first parameter is the set of independent variables, the second parameter is the dependent variable
#The 'test_size' parameter determines the size of the testing dataset. Here we will be using 20% of the dataset for testing
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

In [56]:
#Model Creating
#Creating an instance for Naive Bayes Classifier model
classifier = GaussianNB()

#fitting the training set into the model
classifier.fit(X_train, y_train)

GaussianNB()

In [57]:
#Predicting test results
y_predictions = classifier.predict(X_test)

#Printing the prediction results
print(y_predictions)

['Iris-virginica' 'Iris-virginica' 'Iris-versicolor' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor' 'Iris-virginica'
 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor'
 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor'
 'Iris-setosa' 'Iris-virginica' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-virginica']


In [58]:
#Creating a confusion matrix to check the accuracy of our model
confusion_mat = confusion_matrix(y_test, y_predictions)

#Evaluating the accuracy score
accuracy = accuracy_score(y_test, y_predictions)

#Printing the accuracy score and confusion matrix
print("Accuracy: ", accuracy)
print("Confusion matrix:\n", confusion_mat)

Accuracy:  0.9666666666666667
Confusion matrix:
 [[10  0  0]
 [ 0  8  0]
 [ 0  1 11]]
